#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri --url-ignore '/fonts.gstatic.com/' --href-ignore https://www.linkedin.com/in/jessholbrook/,https://www.linkedin.com/in/naticatalan/,https://www.linkedin.com/in/sven-cattell-5748a311/
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-cayman.gemspec
