#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri --disable_external --url-ignore '/fonts.gstatic.com/'
bundle exec script/validate-html
gem build jekyll-theme-cayman.gemspec
